version: "3"

services:
  postgresdb:
    image: 'postgres:alpine3.17'
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      # If your wanna nopass authentication, 
      # you can use the following option:
      # POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: unless-stopped
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    container_name: postgresdb

  # Uncommit pgadmin if necessary
  # pgadmin4:
  #   image: 'dpage/pgadmin4:2023-01-16-3'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: example@example.com
  #     PGADMIN_DEFAULT_PASSWORD: pgadmin
  #   restart: unless-stopped
  #   ports:
  #     - "8432:80"
  #   container_name: pgadmin4